"""S6 benchmark: fit time and peak memory, rftvc vs scikit-survival RSF (not a merge gate).

Run from the repo root: .venv/bin/python -m bench.compare
Writes docs/bench/s6-perf.md. Each (arm, size) runs in its own process under
``/usr/bin/time -l`` (peak RSS). Matched settings: 100 trees, leaf size 15,
max_features="sqrt", bootstrap with max_samples=0.632, 10 threads; rftvc uses
min_events_leaf=1 (sksurv has no event minimum). Escalation: the next size
runs only if the previous took < 600 s and its peak RSS x 10 < 12 GB.
Discrimination: Harrell's C on a fixed 5,000-subject test set (risk by the
median follow-up for rftvc; ``predict`` for sksurv).
"""

import json
import re
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parents[1] / "docs" / "bench" / "s6-perf.md"
SIZES = [10_000, 100_000, 1_000_000]
ARMS = {
    "rftvc exact": dict(lib="rftvc", ntime=None, rpi=1),
    "rftvc ntime=100": dict(lib="rftvc", ntime=100, rpi=1),
    "sksurv RSF": dict(lib="sksurv", low_memory=False, rpi=1),
    "sksurv RSF low_memory": dict(lib="sksurv", low_memory=True, rpi=1),
    "rftvc exact, TVC 5 rows/id": dict(lib="rftvc", ntime=None, rpi=5),
    "rftvc ntime=100, TVC 5 rows/id": dict(lib="rftvc", ntime=100, rpi=5),
}
COMMON = dict(n_estimators=100, max_features="sqrt", bootstrap=True, max_samples=0.632, n_jobs=10, random_state=0)
TIMEOUT = 1800


def run_one(arm, n):
    """Child process: fit once, print a JSON line."""
    from sksurv.metrics import concordance_index_censored

    from bench.perf_fit import synth

    cfg = ARMS[arm]
    X, y, ids = synth(n, rows_per_id=cfg["rpi"], seed=0)
    Xt, yt, _ = synth(5_000, seed=1)
    if cfg["lib"] == "rftvc":
        from rftvc import SurvivalForestTV

        est = SurvivalForestTV(min_ids_leaf=15, min_events_leaf=1, ntime=cfg["ntime"], **COMMON)
        t0 = time.perf_counter()
        est.fit(X, y, ids)
        fit_s = time.perf_counter() - t0
        risk = est.predict_risk(Xt, float(np.median(yt["stop"])))
    else:
        from sksurv.ensemble import RandomSurvivalForest
        from sksurv.util import Surv

        est = RandomSurvivalForest(min_samples_leaf=15, low_memory=cfg["low_memory"], **COMMON)
        t0 = time.perf_counter()
        est.fit(X, Surv.from_arrays(y["event"], y["stop"]))
        fit_s = time.perf_counter() - t0
        risk = est.predict(Xt)
    c = concordance_index_censored(yt["event"], yt["stop"], risk)[0]
    print(json.dumps({"fit_s": fit_s, "cindex": c, "rows": int(X.shape[0])}))


def measure(arm, n):
    cmd = ["/usr/bin/time", "-l", sys.executable, "-m", "bench.compare", "--one", arm, str(n)]
    try:
        p = subprocess.run(cmd, capture_output=True, text=True, timeout=TIMEOUT)
    except subprocess.TimeoutExpired:
        return {"status": f"timeout > {TIMEOUT} s"}
    rss = re.search(r"(\d+)\s+maximum resident set size", p.stderr)
    lines = [ln for ln in p.stdout.splitlines() if ln.startswith("{")]
    if p.returncode != 0 or not lines:
        tail = p.stderr.strip().splitlines()[-1:] or ["?"]
        return {"status": f"failed (exit {p.returncode}: {tail[0][:80]})",
                "rss_gb": int(rss.group(1)) / 1e9 if rss else None}
    return {"status": "ok", **json.loads(lines[-1]), "rss_gb": int(rss.group(1)) / 1e9}


def main():
    results = {}
    for arm in ARMS:
        prev = None
        for n in SIZES:
            if prev and (prev.get("status") != "ok" or prev["fit_s"] > 600 or prev["rss_gb"] * 10 > 12):
                why = prev["status"].removeprefix("skipped (").removesuffix(")") if prev.get("status") != "ok" else (
                    f"projected ~{prev['fit_s'] * 10:.0f} s / ~{prev['rss_gb'] * 10:.0f} GB")
                results[(arm, n)] = {"status": f"skipped ({why})"}
                prev = results[(arm, n)]
                continue
            r = measure(arm, n)
            results[(arm, n)] = prev = r
            print(arm, n, r, flush=True)
    lines = [
        "# S6: fit time and peak memory vs scikit-survival RSF",
        "",
        "Generated by `bench/compare.py` (M-series Mac, 10 cores, 16 GB). Synthetic right-censored data,",
        "p = 10 (`bench/perf_fit.py::synth`); the TVC arms split each subject into 5 rows with a",
        "time-varying x0. Matched settings: 100 trees, leaf size 15, `max_features=\"sqrt\"`, bootstrap",
        "with `max_samples=0.632`, 10 threads; rftvc `min_events_leaf=1`. Peak RSS of the whole process",
        "(`/usr/bin/time -l`). C = Harrell's C on a fixed 5,000-subject test set.",
        "",
        "| arm | rows | fit (s) | peak RSS (GB) | C | note |",
        "|---|---|---|---|---|---|",
    ]
    for (arm, n), r in results.items():
        if r.get("status") == "ok":
            lines.append(f"| {arm} | {r['rows']:,} | {r['fit_s']:.1f} | {r['rss_gb']:.2f} | {r['cindex']:.3f} | |")
        else:
            lines.append(f"| {arm} | {n:,} | | | | {r['status']} |")
    OUT.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--one":
        run_one(sys.argv[2], int(sys.argv[3]))
    else:
        main()
