"""S2 benchmark report: rftvc vs scikit-survival RSF on GBSG2 (fixed covariates).

Not a merge gate. Run from the repo root:

    .venv/bin/python bench/gbsg2_vs_sksurv.py

Writes docs/bench/s2-gbsg2.md. Protocol (committed so results are reproducible):
- Data: sksurv.datasets.load_gbsg2, categorical columns one-hot encoded.
- Folds: KFold(5, shuffle=True, random_state=0).
- Parameter mapping: one row per id, so min_ids_leaf == min_samples_leaf.
  sksurv has no minimum-events rule, so rftvc uses min_events_leaf=1 in the parity run.
- Risk score for C-index: sum of the cumulative hazard over the training event
  times (the definition sksurv's RandomSurvivalForest.predict uses).
- IBS: sksurv.metrics.integrated_brier_score on the 10th–80th percentiles of the
  test times, clipped to the training follow-up.
"""

import platform
import time
from pathlib import Path

import numpy as np
from sklearn.model_selection import KFold
from sksurv.column import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.ensemble import RandomSurvivalForest
from sksurv.metrics import concordance_index_censored, integrated_brier_score

from rftvc import SurvivalForestTV, make_survival_y

OUT = Path(__file__).resolve().parents[1] / "docs" / "bench" / "s2-gbsg2.md"
N_TREES, LEAF, SEED = 500, 15, 0


def models():
    common = dict(n_estimators=N_TREES, random_state=SEED, n_jobs=-1)
    return {
        "sksurv RSF (bootstrap)": RandomSurvivalForest(
            min_samples_leaf=LEAF, min_samples_split=2 * LEAF, max_features="sqrt", **common
        ),
        "rftvc parity (bootstrap)": SurvivalForestTV(
            bootstrap=True, min_ids_leaf=LEAF, min_events_leaf=1, **common
        ),
        "rftvc defaults (subsample 0.632, hazard)": SurvivalForestTV(**common),
    }


def fit_predict(model, X_tr, y_tr, X_te, times):
    if isinstance(model, SurvivalForestTV):
        y = make_survival_y(y_tr["time"], y_tr["cens"])
        t0 = time.perf_counter()
        model.fit(X_tr, y)
        fit_s = time.perf_counter() - t0
        risk = model.predict_cumulative_hazard(X_te).sum(axis=1)
        surv = model.predict_survival_function(X_te, times)
    else:
        t0 = time.perf_counter()
        model.fit(X_tr, y_tr)
        fit_s = time.perf_counter() - t0
        risk = model.predict(X_te)
        surv = np.vstack([fn(times) for fn in model.predict_survival_function(X_te)])
    return fit_s, risk, surv


def main():
    X, y = load_gbsg2()
    X = encode_categorical(X).to_numpy(dtype=float)
    folds = list(KFold(5, shuffle=True, random_state=SEED).split(X))
    rows = []
    for name, template in models().items():
        cs, ibss, fits = [], [], []
        for tr, te in folds:
            y_tr, y_te = y[tr], y[te]
            lo, hi = np.percentile(y_te["time"], [10, 80])
            hi = min(hi, y_tr["time"].max() - 1)
            times = np.linspace(lo, hi, 50)
            model = type(template)(**template.get_params())
            fit_s, risk, surv = fit_predict(model, X[tr], y_tr, X[te], times)
            cs.append(concordance_index_censored(y_te["cens"], y_te["time"], risk)[0])
            ibss.append(integrated_brier_score(y_tr, y_te, surv, times))
            fits.append(fit_s)
        rows.append((name, np.mean(cs), np.std(cs), np.mean(ibss), np.std(ibss), np.mean(fits)))
        print(f"{name}: C={np.mean(cs):.4f} IBS={np.mean(ibss):.4f} fit={np.mean(fits):.2f}s")

    import sksurv

    import rftvc

    lines = [
        "# S2 benchmark: GBSG2, rftvc vs scikit-survival",
        "",
        f"Generated by `bench/gbsg2_vs_sksurv.py`. {N_TREES} trees, 5-fold CV (seed {SEED}), "
        f"{X.shape[0]} rows, {X.shape[1]} features.",
        f"Machine: {platform.machine()} / {platform.system()}, rftvc {rftvc.__version__}, "
        f"scikit-survival {sksurv.__version__}, all cores (`n_jobs=-1`).",
        "",
        "| Model | C-index (mean ± sd) | IBS (mean ± sd) | Fit time per fold (s) |",
        "|---|---|---|---|",
    ]
    for name, c, csd, ibs, ibssd, fit in rows:
        lines.append(f"| {name} | {c:.4f} ± {csd:.4f} | {ibs:.4f} ± {ibssd:.4f} | {fit:.2f} |")
    parity = {r[0]: r for r in rows}
    dc = parity["rftvc parity (bootstrap)"][1] - parity["sksurv RSF (bootstrap)"][1]
    dibs = parity["rftvc parity (bootstrap)"][3] - parity["sksurv RSF (bootstrap)"][3]
    lines += [
        "",
        f"Parity differences (rftvc − sksurv): ΔC = {dc:+.4f}, ΔIBS = {dibs:+.4f}.",
        "",
        "Tolerance rationale (±0.02): the two implementations differ by design in ways that",
        "shift results slightly without either being wrong. rftvc bins features into ≤255",
        "histogram bins; sksurv splits on exact values. rftvc requires a positive log-rank",
        "score to split. The random streams and tie-breaking also differ. The fold-to-fold sd",
        f"of the sksurv C-index here is {parity['sksurv RSF (bootstrap)'][2]:.3f}, so parity differences",
        "inside ±0.02 are well within fold noise.",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
