"""Slice 2 (docs/plans/plan.md): lifelines cross-check against known truth
(genuinely static DGP).

Data-generating process (new for this slice — deliberately *not* a reuse of
``tests.sim``'s time-varying one; per the plan review, subsetting a
time-varying DGP to one covariate does not make its conditional survival
truth static, since the redrawn covariate still drives the actual hazard):

- Subjects have a single covariate ``x ~ N(0, 1)``, fixed for the subject's
  entire observation (never redrawn) — genuinely static.
- Constant-baseline proportional hazard: ``rate(x) = lambda0 * exp(beta * x)``,
  ``T ~ Exponential(rate(x))``. Closed form: ``S(t | x) = exp(-lambda0 * t *
  exp(beta * x))``.
- Censoring ``C ~ Uniform(2, 8)``, administrative end at 8; evaluation grid
  ``[0, 6]``.

Comparator: ``lifelines.CoxPHFitter``, not ``CoxTimeVaryingFitter`` — the
correct choice specifically *because* this DGP is static (the original plan
draft named ``CoxTimeVaryingFitter`` as unusable for TVC and picked
``KaplanMeierFitter`` instead, which was wrong on both counts:
``CoxTimeVaryingFitter`` does handle TVC, and ``KaplanMeierFitter`` ignores
covariates entirely, so it isn't a fair comparator against a covariate-driven
truth). ``CoxPHFitter`` is the textbook-correct semi-parametric tool for a
static, single-covariate proportional-hazards DGP, and this DGP exactly
matches its assumptions — so it is expected to substantially outperform
``SurvivalForestTV`` here (confirmed by an out-of-band pilot, seeds
``10_000..10_004``, 5 replications at this module's own defaults —
n_train=400, n_test=200, n_estimators=200: per-seed (rftvc_ISE, cox_ISE) =
(0.0228, 0.0036), (0.0359, 0.0033), (0.0484, 0.0066), (0.0619, 0.0040),
(0.0347, 0.0014); mean rftvc_ISE ≈ 0.0407, mean cox_ISE ≈ 0.0038, mean gap
≈ 0.0369). That gap is the DGP being
sanity check that ``rftvc`` isn't a statistical *outlier* on the model's own
terms, not a claim that it should beat a hand-fit Cox model on data
generated by a Cox model.

Metric: integrated squared error (ISE) of predicted ``S(t | x)`` vs the true
``S(t | x)`` over ``t ∈ [0, 6]`` (trapezoid rule, 61 points), averaged over
test subjects — same convention as ``tests/sim.py``.

Pass rule (declared here, before the gate's own R=10 replications were run,
using an epsilon calibrated from the out-of-band pilot above, not from these
seeds): over R=10 replications (seeds 0-9), ``mean(rftvc_ISE) <=
mean(cox_ISE) + 0.08`` — roughly double the pilot's observed gap, enough
headroom for run-to-run variability while still failing if
``SurvivalForestTV``'s ISE were an order of magnitude worse than observed
(which would indicate a real regression, not just lower statistical
efficiency on a Cox-ideal DGP). An additive tolerance is used instead of a
ratio to the best-observed ISE, since the reference ISE here is small and a
ratio would be unstable near a near-zero denominator (per plan review).

Scope: single-event, static-covariate only. Does not exercise TVC or
competing risks — those stay covered by Slice 1 and the existing
``bench/*_sim.py`` suites.
"""

import numpy as np
import pandas as pd
from lifelines import CoxPHFitter

from rftvc import SurvivalForestTV, make_survival_y

LAMBDA0 = 0.2
BETA = 0.7
HORIZON = 6.0
END = 8.0
GRID = np.linspace(0.0, HORIZON, 61)
EPSILON = 0.08  # calibrated from an out-of-band pilot (seeds >= 10_000), see module docstring


def true_survival(x, t):
    """S(t | x) = exp(-lambda0 * t * exp(beta * x)), static x, constant baseline hazard."""
    x = np.asarray(x, dtype=float)[:, None]
    t = np.asarray(t, dtype=float)[None, :]
    return np.exp(-LAMBDA0 * t * np.exp(BETA * x))


def simulate(n, rng):
    x = rng.normal(size=n)
    rate = LAMBDA0 * np.exp(BETA * x)
    T = rng.exponential(1.0 / rate)
    C = rng.uniform(2.0, END, size=n)
    U = np.minimum(T, C)
    event = T <= C
    return x, U, event


def ise(s_hat, s_true):
    return np.trapezoid((s_hat - s_true) ** 2, GRID, axis=1).mean()


def _rftvc_survival(x_train, U, event, x_test, seed, n_estimators):
    m = SurvivalForestTV(n_estimators=n_estimators, random_state=seed).fit(
        x_train[:, None], make_survival_y(U, event)
    )
    return m.predict_survival_function(x_test[:, None], GRID)


def _coxph_survival(x_train, U, event, x_test):
    df = pd.DataFrame({"x": x_train, "T": U, "event": event})
    cph = CoxPHFitter().fit(df, duration_col="T", event_col="event")
    sf = cph.predict_survival_function(pd.DataFrame({"x": x_test}), times=GRID)
    return sf.to_numpy().T


def replicate(seed, n_train=400, n_test=200, n_estimators=200):
    """One replication's (rftvc_ISE, cox_ISE) against the closed-form truth.

    ``x`` is fixed per subject at draw time and never modified afterwards —
    it is a genuinely static covariate, not a time-varying one subset to one
    column.
    """
    rng = np.random.default_rng(seed)
    x_tr, U, event = simulate(n_train, rng)
    x_te, _, _ = simulate(n_test, rng)
    s_true = true_survival(x_te, GRID)
    s_rftvc = _rftvc_survival(x_tr, U, event, x_te, seed, n_estimators)
    s_cox = _coxph_survival(x_tr, U, event, x_te)
    return ise(s_rftvc, s_true), ise(s_cox, s_true)


def run(n_reps=10, seed0=0, **kw):
    """(n_reps, 2) array of (rftvc_ISE, cox_ISE) per replication, seeds ``seed0..seed0+n_reps-1``."""
    return np.array([replicate(seed0 + r, **kw) for r in range(n_reps)])
