"""S5 accept example: nested rolling-origin CV of a landmark forest on a simulated panel.

Run from the repo root: .venv/bin/python -m bench.s5_nested_cv
Writes docs/bench/s5-nested-cv.md. The DGP is in tests/sim_panel.py.
"""

import time
from pathlib import Path

import numpy as np
import polars as pl

from rftvc import LandmarkSurvivalForest, SurvivalForestTV, make_landmark_data
from rftvc.metrics import calibration_table
from rftvc.model_selection import RollingOriginSplit, landmark_cross_validate
from tests.sim_panel import simulate_panel

OUT = Path(__file__).resolve().parents[1] / "docs" / "bench" / "s5-nested-cv.md"
H, STEP = 6.0, 3.0
FEATURES = ["x", ("x", "mean"), ("x", "max"), "z"]
SCORING = ["brier", "integrated_brier", "cindex_cumulative", "cindex_incident"]


def main():
    df = simulate_panel(n_units=2000, n_periods=96, seed=0)
    model = LandmarkSurvivalForest(
        horizon=H, history_features=FEATURES, step=STEP,
        forest=SurvivalForestTV(n_estimators=200, random_state=0, n_jobs=-1),
    )
    outer = RollingOriginSplit(3, test_size=12, gap=H)
    inner = RollingOriginSplit(2, test_size=12, gap=H)
    grid = {"forest__min_ids_leaf": [5, 15, 50]}
    t0 = time.perf_counter()
    res = landmark_cross_validate(model, df, outer, scoring=SCORING, param_grid=grid, inner_cv=inner, refit="brier")
    elapsed = time.perf_counter() - t0

    data = make_landmark_data(df, horizon=H, step=STEP, history_features=FEATURES)
    summary = res.group_by("fold", maintain_order=True).agg(
        pl.col("params").first(),
        pl.col("landmark").min().alias("first_s"),
        pl.col("landmark").max().alias("last_s"),
        pl.col("n").sum(),
        pl.col("n_cases").sum(),
        pl.col("n_clipped").sum(),
        *[pl.col(m).fill_nan(None).mean() for m in SCORING],
    )

    # Calibration of the last fold, pooled over its test landmarks (single fit on data before them).
    last = res.filter(pl.col("fold") == res["fold"].max())
    cutoff = last["landmark"].min()
    train_s = np.unique(data.s[data.s <= cutoff - H])
    from rftvc.model_selection import _censor_at

    fitted = model.set_params(landmarks=train_s, step=None).fit(
        _censor_at(df, cutoff, start="start", stop="stop", event="event")
    )
    m = data.s >= cutoff
    risk = 1 - fitted.forest_.predict_survival_function(data.X[m], [H])[:, 0]
    cal = calibration_table(data.y[m], risk, H, n_bins=10)

    lines = [
        "# S5: nested rolling-origin CV on a simulated panel",
        "",
        "Generated by `bench/s5_nested_cv.py`; DGP in `tests/sim_panel.py` (2,000 units × 96 periods,",
        f"AR(1) external covariate, onset hazard with a threshold effect). Landmarks every {STEP:g} periods,",
        f"horizon {H:g}. Outer: `RollingOriginSplit(3, test_size=12, gap={H:g})`; inner: 2 folds, same window/gap;",
        f"grid `min_ids_leaf` ∈ {grid['forest__min_ids_leaf']}, selected by mean inner Brier. 200 trees.",
        f"Censoring weights: reverse KM on each test landmark's risk set (`G_s`), `g_min = 0.05`. Wall time {elapsed:.0f} s.",
        "",
        "Per outer fold (means over its test landmarks):",
        "",
        "| fold | selected | landmarks | n | cases | clipped | Brier | IBS | C/D AUC | Uno C |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in summary.iter_rows(named=True):
        lines.append(
            f"| {r['fold']} | {r['params']} | {r['first_s']:g}–{r['last_s']:g} | {r['n']} | {r['n_cases']} | "
            f"{r['n_clipped']} | {r['brier']:.4f} | {r['integrated_brier']:.4f} | "
            f"{r['cindex_cumulative']:.3f} | {r['cindex_incident']:.3f} |"
        )
    prev = float(np.mean(data.y[m]["event"]))
    lines += [
        "",
        f"Last fold, pooled over its test landmarks: calibration at w = {H:g} (quantile bins of predicted risk;",
        f"observed = 1 − KM within bin). Share of test rows with an observed event: {prev:.3f}.",
        "",
        "| bin | n | events | mean predicted | observed |",
        "|---|---|---|---|---|",
    ]
    for r in cal.iter_rows(named=True):
        lines.append(f"| {r['bin']} | {r['n']} | {r['n_events']} | {r['mean_risk']:.3f} | {r['observed_risk']:.3f} |")
    OUT.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
