"""S9: forest storage before and after leaf slimming, at 1M rows.

Run each mode once on a `main` build and once on the S9 build, then report:

    python -m bench.s9_leaf rss OUT.jsonl      # fit time + peak RSS (bench/compare.py arms)
    python -m bench.s9_leaf storage OUT.jsonl  # node / leaf / entry counts, pickle bytes
    python -m bench.s9_leaf report MAIN_DIR S9_DIR   # -> docs/bench/s9-leaf.md

Storage runs separately from the RSS runs: pickling a fitted forest copies it,
which would inflate the peak RSS of the timed process.
"""

import json
import pickle
import sys
from pathlib import Path

from bench.compare import ARMS, COMMON, measure
from bench.perf_fit import synth

N = 1_000_000
RFTVC_ARMS = [a for a in ARMS if ARMS[a]["lib"] == "rftvc"]
NODE_BYTES = 24  # size_of::<Node>()
OLD_LEAF_BYTES = 96  # four Vec headers per leaf (event_idx, d, y, cumhaz)


def rss(out):
    with open(out, "w") as f:
        for arm in RFTVC_ARMS:
            f.write(json.dumps({"arm": arm, **measure(arm, N)}) + "\n")
            f.flush()


def storage(out):
    from rftvc import SurvivalForestTV

    with open(out, "w") as f:
        for arm in RFTVC_ARMS:
            cfg = ARMS[arm]
            X, y, ids = synth(N, rows_per_id=cfg["rpi"], seed=0)
            est = SurvivalForestTV(min_ids_leaf=15, min_events_leaf=1, ntime=cfg["ntime"], **COMMON).fit(X, y, ids)
            s = est.forest_.__reduce__()[1][0]
            rec = {
                "arm": arm,
                "trees": len(s["tree_seeds"]),
                "nodes": len(s["node_feature"]),
                "leaves": len(s["event_offsets"]) - 1,
                "entries": len(s["event_idx"]),
                "grid": len(s["grid"]),
                "pickle_bytes": len(pickle.dumps(est.forest_, protocol=5)),
                "nbytes": getattr(est.forest_, "nbytes", None),
                "format": "v1 (d, y, cumhaz)" if "d" in s else "v2 (cumhaz)",
            }
            f.write(json.dumps(rec) + "\n")
            f.flush()


def _logical_old(r):
    """In-memory bytes of the pre-S9 layout: a lower bound (no allocator or capacity slack)."""
    return NODE_BYTES * r["nodes"] + OLD_LEAF_BYTES * r["leaves"] + 28 * r["entries"] + 8 * r["grid"]


def _load(path):
    return {r["arm"]: r for r in map(json.loads, Path(path).read_text().splitlines()) if r}


def report(main_dir, s9_dir):
    rm, rs = _load(Path(main_dir) / "rss.jsonl"), _load(Path(s9_dir) / "rss.jsonl")
    sm, ss = _load(Path(main_dir) / "storage.jsonl"), _load(Path(s9_dir) / "storage.jsonl")
    gb = 1e9
    lines = [
        "# S9: leaf-storage slimming at 1M rows",
        "",
        "Generated by `bench/s9_leaf.py` (M-series Mac, 10 cores, 16 GB), same data and settings as",
        "`bench/compare.py` (100 trees, leaf size 15, `max_features=\"sqrt\"`, subsample 0.632, 10 threads).",
        "`main` = before S9, `S9` = this slice. Forest bytes: `main` is the logical size of the old layout",
        f"({NODE_BYTES} B per node, {OLD_LEAF_BYTES} B of `Vec` headers per leaf, 28 B per leaf event time; no",
        "allocator or capacity slack, so a lower bound); `S9` is `forest_.nbytes` (allocated capacity of",
        "the node and leaf arrays, which are shrunk to fit). Both include one copy of the grid.",
        "",
        "| arm | leaves | leaf event times | forest GB main → S9 | pickle GB main → S9 | peak RSS GB main → S9 | fit s main → S9 |",
        "|---|---|---|---|---|---|---|",
    ]
    for arm in RFTVC_ARMS:
        a, b = sm[arm], ss[arm]
        assert (a["leaves"], a["entries"]) == (b["leaves"], b["entries"]), f"{arm}: different forests"
        old, new = _logical_old(a), b["nbytes"]
        lines.append(
            f"| {arm} | {a['leaves']:,} | {a['entries']:,} "
            f"| {old / gb:.2f} → {new / gb:.2f} (−{1 - new / old:.0%}) "
            f"| {a['pickle_bytes'] / gb:.2f} → {b['pickle_bytes'] / gb:.2f} (−{1 - b['pickle_bytes'] / a['pickle_bytes']:.0%}) "
            f"| {rm[arm]['rss_gb']:.2f} → {rs[arm]['rss_gb']:.2f} "
            f"| {rm[arm]['fit_s']:.1f} → {rs[arm]['fit_s']:.1f} |"
        )
    out = Path("docs/bench/s9-leaf.md")
    out.write_text("\n".join(lines) + "\n")
    print(out.read_text())


if __name__ == "__main__":
    mode, *args = sys.argv[1:]
    {"rss": rss, "storage": storage, "report": report}[mode](*args)
